project_id = "xuncvfnvatgqshlivuep"

# ============================================
# PROTECTED CORE INTELLIGENCE FUNCTIONS (10)
# These provide system-wide orchestration
# ============================================

[functions.mega-mind-orchestrator]
verify_jwt = true

[functions.mega-mind-self-healer]
verify_jwt = false

[functions.advanced-reasoning-engine]
verify_jwt = false

[functions.proactive-monitor]
verify_jwt = false

[functions.proactive-intelligence]
verify_jwt = true

[functions.self-learning-engine]
verify_jwt = false

[functions.pattern-recognizer]
verify_jwt = false

[functions.predictive-alert-engine]
verify_jwt = false

[functions.autonomous-healing-engine]
verify_jwt = false

[cron.autonomous_healing]
# Run autonomous healing every 5 minutes
schedule = "*/5 * * * *"
function_name = "autonomous-healing-engine"

[functions.meta-self-improvement]
verify_jwt = false

[functions.security-intelligence]
verify_jwt = false

[functions.confirmation-engine]
verify_jwt = true

[functions.conversation-intelligence]
verify_jwt = true

# ============================================
# AGI SELF-CORRECTING SYSTEM (3)
# Autonomous decision validation and learning
# ============================================

[functions.decision-validator]
verify_jwt = false

[functions.meta-learning-engine]
verify_jwt = false

[functions.autonomous-corrector]
verify_jwt = false

[functions.auto-test-runner]
verify_jwt = false

[cron.auto_test_runner]
# Run production tests every 6 hours
schedule = "0 */6 * * *"
function_name = "auto-test-runner"

[functions.progressive-enhancer]
verify_jwt = true

# ============================================
# UNIFIED WORKER FUNCTIONS (20)
# Enterprise-grade consolidated operations
# ============================================

[functions.unified-ai-workers]
verify_jwt = false

[functions.unified-code-operations]
verify_jwt = true

[functions.unified-deployment]
verify_jwt = true

[functions.unified-infrastructure]
verify_jwt = true

[functions.unified-monitoring]
verify_jwt = false

[functions.unified-learning]
verify_jwt = true

[functions.unified-quality]
verify_jwt = true

[functions.unified-package-manager]
verify_jwt = true

[functions.unified-healing-engine]
verify_jwt = true

[functions.unified-test-manager]
verify_jwt = true

[functions.unified-automation]
verify_jwt = true

[functions.unified-notifications]
verify_jwt = false

[functions.unified-cache-manager]
verify_jwt = true

[functions.unified-resource-manager]
verify_jwt = true

[functions.unified-analytics]
verify_jwt = false

[functions.unified-security]
verify_jwt = false

[functions.unified-snapshot-manager]
verify_jwt = true

[functions.unified-webhook-manager]
verify_jwt = true

[functions.unified-backup-manager]
verify_jwt = true

[functions.unified-rate-limiter]
verify_jwt = false

# ============================================
# VERCEL INTEGRATION
# Production deployment pipeline
# ============================================

[functions.vercel-integration]
verify_jwt = true

[functions.test-supabase-connection]
verify_jwt = true

[functions.analytics-aggregator]
verify_jwt = false

[functions.report-error]
verify_jwt = false
