project_id = "xuncvfnvatgqshlivuep"

[functions.intelligent-conversation]
verify_jwt = false

[functions.ai-code-builder]
verify_jwt = false

[functions.generate-website]
verify_jwt = false

[functions.chat-generate]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.analyze-code]
verify_jwt = false

[functions.optimize-code]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.design-to-code]
verify_jwt = false

[functions.accessibility-check]
verify_jwt = false

[functions.seo-analyze]
verify_jwt = false

[functions.security-scan]
verify_jwt = false

[functions.api-generate]
verify_jwt = false

[functions.meta-improve]
verify_jwt = true

[functions.self-heal]
verify_jwt = false

[functions.ai-reflect]
verify_jwt = false

[functions.scheduled-improvement]
verify_jwt = false

[functions.admin-self-modify]
verify_jwt = true

[functions.rollback-customization]
verify_jwt = true

[functions.save-snapshot]
verify_jwt = true

[functions.restore-snapshot]
verify_jwt = true

[functions.report-error]
verify_jwt = false

[functions.auto-fix-engine]
verify_jwt = false

[functions.apply-fix]
verify_jwt = false

[functions.proactive-monitor]
verify_jwt = false

[functions.code-quality-analyzer]
verify_jwt = false

[functions.create-modification]
verify_jwt = false

[functions.generate-tests]
verify_jwt = true

[functions.learn-from-conversation]
verify_jwt = true

[functions.meta-improve]
verify_jwt = true

[functions.manage-preferences]
verify_jwt = true

[functions.suggest-refactoring]
verify_jwt = true

[functions.audit-dependencies]
verify_jwt = true

[functions.generate-docs]
verify_jwt = true

[functions.generate-with-plan]
verify_jwt = false

[functions.smart-diff-update]
verify_jwt = false

[functions.learn-user-preferences]
verify_jwt = false

[functions.multi-project-learn]
verify_jwt = false

[functions.iterative-refine]
verify_jwt = false

[functions.component-awareness]
verify_jwt = false

[functions.smart-orchestrator]
verify_jwt = false

[functions.model-selector]
verify_jwt = false

[functions.feedback-processor]
verify_jwt = false

[functions.learn-pattern]
verify_jwt = false

[functions.multi-file-generate]
verify_jwt = true

[functions.refactor-code]
verify_jwt = true

[functions.advanced-reasoning]
verify_jwt = false

[functions.self-reflection]
verify_jwt = false

[functions.proactive-intelligence]
verify_jwt = false

[functions.knowledge-ingest]
verify_jwt = false

[functions.dockerfile-agent]
verify_jwt = false

[functions.generate-ai-image]
verify_jwt = true

[functions.intelligent-refactor]
verify_jwt = true

[functions.proactive-intelligence]
verify_jwt = true

[functions.react-component-generator]
verify_jwt = true

[functions.generate-tests]
verify_jwt = false

[functions.save-database-credentials]
verify_jwt = true

[functions.test-database-connection]
verify_jwt = true

[functions.list-database-credentials]
verify_jwt = true

[functions.check-database-health]
verify_jwt = true

[functions.delete-database-credentials]
verify_jwt = true

[functions.get-security-metrics]
verify_jwt = true

[functions.get-security-audit-logs]
verify_jwt = true

[functions.analyze-database-error]
verify_jwt = true

[functions.validate-database-config]
verify_jwt = true

[functions.fetch-provider-docs]
verify_jwt = false

[functions.proactive-health-monitor]
verify_jwt = false

[functions.learn-connection-knowledge]
verify_jwt = false

[functions.intelligent-retry-connection]
verify_jwt = true

[functions.setup-monitoring-cron]
verify_jwt = true

[functions.send-alert-notification]
verify_jwt = false

[functions.predict-failure]
verify_jwt = true

[functions.optimize-connection-cost]
verify_jwt = true

[functions.deployment-fix-teacher]
verify_jwt = true

[functions.universal-error-teacher]
verify_jwt = true

[functions.fetch-documentation]
verify_jwt = false

[functions.auto-install-dependency]
verify_jwt = true

