project_id = "xuncvfnvatgqshlivuep"

# ============================================
# PROTECTED CORE INTELLIGENCE FUNCTIONS (10)
# These provide system-wide orchestration
# ============================================

[functions.mega-mind-orchestrator]
verify_jwt = true

[functions.mega-mind-self-healer]
verify_jwt = true  # SECURITY: Requires authentication

[functions.backend-self-monitor]
verify_jwt = true  # SECURITY: Requires authentication

[functions.unified-autonomous-coordinator]
verify_jwt = true  # SECURITY: Requires authentication

[functions.advanced-reasoning-engine]
verify_jwt = true  # SECURITY: Requires authentication

[functions.proactive-monitor]
verify_jwt = true  # SECURITY: Requires authentication

[functions.proactive-intelligence]
verify_jwt = true

[functions.self-learning-engine]
verify_jwt = true  # SECURITY: Requires authentication

[functions.pattern-recognizer]
verify_jwt = true  # SECURITY: Requires authentication

[functions.predictive-alert-engine]
verify_jwt = true  # SECURITY: Requires authentication

[functions.autonomous-healing-engine]
verify_jwt = true  # SECURITY: Requires authentication

[cron.autonomous_healing]
# Run autonomous healing every 5 minutes
schedule = "*/5 * * * *"
function_name = "autonomous-healing-engine"

[functions.meta-self-improvement]
verify_jwt = true  # SECURITY: Requires authentication

[functions.security-intelligence]
verify_jwt = true  # SECURITY: Requires authentication

[functions.confirmation-engine]
verify_jwt = true

[functions.conversation-intelligence]
verify_jwt = true

# ============================================
# AGI SELF-CORRECTING SYSTEM (3)
# Autonomous decision validation and learning
# ============================================

[functions.decision-validator]
verify_jwt = true

[functions.meta-learning-engine]
verify_jwt = true

[functions.autonomous-corrector]
verify_jwt = true

[functions.auto-test-runner]
verify_jwt = false

[cron.auto_test_runner]
# Run production tests every 6 hours
schedule = "0 */6 * * *"
function_name = "auto-test-runner"

[functions.progressive-enhancer]
verify_jwt = true

# ============================================
# UNIFIED WORKER FUNCTIONS (20)
# Enterprise-grade consolidated operations
# ============================================

[functions.unified-ai-workers]
verify_jwt = true  # SECURITY: Requires authentication

[functions.unified-code-operations]
verify_jwt = true

[functions.unified-deployment]
verify_jwt = true

[functions.unified-infrastructure]
verify_jwt = true

[functions.unified-monitoring]
verify_jwt = true  # SECURITY: Requires authentication

[functions.unified-learning]
verify_jwt = true

[functions.unified-quality]
verify_jwt = true

[functions.unified-package-manager]
verify_jwt = true

[functions.unified-healing-engine]
verify_jwt = true

[functions.unified-test-manager]
verify_jwt = true

[functions.unified-automation]
verify_jwt = true

[functions.unified-notifications]
verify_jwt = true  # SECURITY: Requires authentication

[functions.unified-cache-manager]
verify_jwt = true

[functions.unified-resource-manager]
verify_jwt = true

[functions.unified-analytics]
verify_jwt = true  # SECURITY: Requires authentication

[functions.unified-security]
verify_jwt = true  # SECURITY: Requires authentication

[functions.unified-snapshot-manager]
verify_jwt = true

[functions.unified-webhook-manager]
verify_jwt = true

[functions.unified-backup-manager]
verify_jwt = true

[functions.unified-rate-limiter]
verify_jwt = true  # SECURITY: Requires authentication for rate limiter management

# ============================================
# VERCEL INTEGRATION
# Production deployment pipeline
# ============================================

[functions.vercel-integration]
verify_jwt = true

[functions.test-supabase-connection]
verify_jwt = true

[functions.analytics-aggregator]
verify_jwt = true  # SECURITY: Requires authentication

[functions.report-error]
verify_jwt = false  # Public endpoint for error reporting with rate limiting

[functions.conversational-ai]
verify_jwt = true

[functions.admin-approval-handler]
verify_jwt = true

[functions.trigger-deployment]
verify_jwt = true  # SECURITY: Requires authentication

[functions.prompt-evolution-engine]
verify_jwt = true  # SECURITY: Requires authentication

# ============================================
# MEGA MIND AGI SYSTEM
# Autonomous development with intelligence
# ============================================

[functions.mega-mind]
verify_jwt = true

# ============================================
# UNIVERSAL ROUTER SYSTEM (Phase 1)
# Fast intent classification and routing
# ============================================

[functions.universal-router]
verify_jwt = true

[functions.direct-code-editor]
verify_jwt = true

# ============================================
# PHASE 2: INTELLIGENT ROUTING ENHANCEMENTS
# Caching, Learning, and Optimization
# ============================================

[functions.intelligent-cache-manager]
verify_jwt = true

[functions.user-preference-learner]
verify_jwt = true

# ============================================
# PHASE 3: MULTI-MODEL ORCHESTRATION
# Quality Scoring and Automatic Fallbacks
# ============================================

[functions.multi-model-orchestrator]
verify_jwt = true

# ============================================
# PROJECT CONTEXT MANAGER
# Intelligent workspace awareness
# ============================================

[functions.project-context-manager]
verify_jwt = true
