project_id = "xuncvfnvatgqshlivuep"

# ============================================
# PROTECTED CORE INTELLIGENCE FUNCTIONS (10)
# These provide system-wide orchestration
# ============================================

[functions.mega-mind-orchestrator]
verify_jwt = true

[functions.mega-mind-self-healer]
verify_jwt = false

[functions.advanced-reasoning-engine]
verify_jwt = false

[functions.proactive-monitor]
verify_jwt = false

[functions.proactive-intelligence]
verify_jwt = true

[functions.self-learning-engine]
verify_jwt = false

[functions.pattern-recognizer]
verify_jwt = false

[functions.predictive-alert-engine]
verify_jwt = false

[functions.autonomous-healing-engine]
verify_jwt = false

[functions.meta-self-improvement]
verify_jwt = false

[functions.process-job-queue]
verify_jwt = false

[functions.code-executor]
verify_jwt = false

# ============================================
# UNIFIED WORKER FUNCTIONS (20)
# Enterprise-grade consolidated operations
# ============================================

[functions.unified-ai-workers]
verify_jwt = false

[functions.unified-code-operations]
verify_jwt = true

[functions.unified-deployment]
verify_jwt = true

[functions.unified-infrastructure]
verify_jwt = true

[functions.unified-monitoring]
verify_jwt = false

[functions.unified-learning]
verify_jwt = true

[functions.unified-quality]
verify_jwt = true

[functions.unified-package-manager]
verify_jwt = true

[functions.unified-healing-engine]
verify_jwt = true

[functions.unified-test-manager]
verify_jwt = true

[functions.unified-automation]
verify_jwt = true

[functions.unified-notifications]
verify_jwt = false

[functions.unified-cache-manager]
verify_jwt = true

[functions.unified-resource-manager]
verify_jwt = true

[functions.unified-analytics]
verify_jwt = false

[functions.unified-security]
verify_jwt = false

[functions.unified-snapshot-manager]
verify_jwt = true

[functions.unified-webhook-manager]
verify_jwt = true

[functions.unified-backup-manager]
verify_jwt = true

[functions.unified-rate-limiter]
verify_jwt = false

[functions.deployment-health-monitor]
verify_jwt = false

# ============================================
# SECURITY & ENCRYPTION FUNCTIONS
# Advanced security features
# ============================================

[functions.encrypt-sensitive-data]
verify_jwt = true

[functions.security-audit]
verify_jwt = true

[functions.ai-code-review]
verify_jwt = true

[functions.smart-debugger]
verify_jwt = true

[functions.send-monitoring-alert]
verify_jwt = false

# ============================================
# DEPLOYMENT & VERCEL INTEGRATION
# Production deployment pipeline
# ============================================

[functions.vercel-connect]
verify_jwt = true

[functions.vercel-deploy]
verify_jwt = true

[functions.vercel-status]
verify_jwt = true

[functions.complete-vercel-pipeline]
verify_jwt = true

[functions.prompt-to-production]
verify_jwt = true

