project_id = "xuncvfnvatgqshlivuep"

[functions.ai-code-builder]
verify_jwt = false

[functions.generate-website]
verify_jwt = false

[functions.chat-generate]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.analyze-code]
verify_jwt = false

[functions.optimize-code]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.design-to-code]
verify_jwt = false

[functions.accessibility-check]
verify_jwt = false

[functions.seo-analyze]
verify_jwt = false

[functions.security-scan]
verify_jwt = false

[functions.api-generate]
verify_jwt = false

[functions.meta-improve]
verify_jwt = true

[functions.self-heal]
verify_jwt = false

[functions.ai-reflect]
verify_jwt = false

[functions.scheduled-improvement]
verify_jwt = false

[functions.admin-self-modify]
verify_jwt = true

[functions.rollback-customization]
verify_jwt = true

[functions.save-snapshot]
verify_jwt = true

[functions.restore-snapshot]
verify_jwt = true

[functions.report-error]
verify_jwt = false

[functions.auto-fix-engine]
verify_jwt = false

[functions.apply-fix]
verify_jwt = false

[functions.proactive-monitor]
verify_jwt = false

[functions.code-quality-analyzer]
verify_jwt = false

[functions.create-modification]
verify_jwt = false

[functions.generate-tests]
verify_jwt = true

[functions.suggest-refactoring]
verify_jwt = true

[functions.audit-dependencies]
verify_jwt = true

[functions.generate-docs]
verify_jwt = true

[functions.generate-with-plan]
verify_jwt = false

[functions.smart-diff-update]
verify_jwt = false