project_id = "xuncvfnvatgqshlivuep"

[functions.generate-website]
verify_jwt = false

[functions.chat-generate]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.analyze-code]
verify_jwt = false

[functions.optimize-code]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.design-to-code]
verify_jwt = false

[functions.accessibility-check]
verify_jwt = false

[functions.seo-analyze]
verify_jwt = false

[functions.security-scan]
verify_jwt = false

[functions.api-generate]
verify_jwt = false

[functions.meta-improve]
verify_jwt = true

[functions.self-heal]
verify_jwt = false

[functions.ai-reflect]
verify_jwt = false

[functions.scheduled-improvement]
verify_jwt = false

[functions.admin-self-modify]
verify_jwt = true

[functions.report-error]
verify_jwt = false

[functions.auto-fix-engine]
verify_jwt = false

[functions.apply-fix]
verify_jwt = false

[functions.proactive-monitor]
verify_jwt = false

[functions.code-quality-analyzer]
verify_jwt = false