import { AIThinkingPanel } from '@/components/AIThinkingPanel';
import { Card } from '@/components/ui/card';
import { Sparkles, FolderOpen, MessageSquare } from 'lucide-react';

/**
 * Demo page showing how AI displays its autonomous thinking process
 * This shows users exactly what the AI is doing and which workspace it's working in
 */
export default function WorkspaceThinkingDemo() {
  // In real usage, these would come from your project context
  const demoProjectId = 'demo-project-123';
  const demoConversationId = 'demo-conversation-456';
  const demoWorkspaceName = 'My Coffee Shop Website';

  return (
    <div className="min-h-screen bg-gradient-to-b from-background via-primary/5 to-background p-6">
      <div className="max-w-5xl mx-auto space-y-6">
        {/* Header */}
        <div className="text-center space-y-3 py-8">
          <div className="flex items-center justify-center gap-2">
            <Sparkles className="h-8 w-8 text-primary" />
            <h1 className="text-4xl font-bold bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
              AI Autonomous Workspace
            </h1>
          </div>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            Watch how the AI autonomously thinks, plans, and builds your project.
            No predefined templates - the AI decides everything based on your request.
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-6">
          {/* Left: AI Thinking Panel */}
          <div className="space-y-4">
            <div className="flex items-center gap-2 px-1">
              <FolderOpen className="h-5 w-5 text-primary" />
              <h2 className="text-lg font-semibold">Workspace Context</h2>
            </div>
            
            <AIThinkingPanel
              projectId={demoProjectId}
              conversationId={demoConversationId}
              workspaceName={demoWorkspaceName}
            />
          </div>

          {/* Right: Explanation */}
          <div className="space-y-4">
            <div className="flex items-center gap-2 px-1">
              <MessageSquare className="h-5 w-5 text-accent" />
              <h2 className="text-lg font-semibold">How It Works</h2>
            </div>

            <Card className="p-6 space-y-4">
              <div className="space-y-3">
                <h3 className="font-semibold text-primary flex items-center gap-2">
                  <span className="flex h-2 w-2">
                    <span className="animate-ping absolute inline-flex h-2 w-2 rounded-full bg-primary opacity-75"></span>
                    <span className="relative inline-flex rounded-full h-2 w-2 bg-primary"></span>
                  </span>
                  1. Workspace Context
                </h3>
                <p className="text-sm text-muted-foreground">
                  The AI knows exactly which project and workspace to work in through:
                </p>
                <ul className="text-sm space-y-1 text-muted-foreground ml-4">
                  <li>• <code className="text-primary">projectId</code> - Where to save files</li>
                  <li>• <code className="text-primary">conversationId</code> - Conversation history</li>
                  <li>• <code className="text-primary">userId</code> - Who's requesting</li>
                </ul>
              </div>

              <div className="space-y-3">
                <h3 className="font-semibold text-accent flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-accent"></span>
                  2. Autonomous Analysis
                </h3>
                <p className="text-sm text-muted-foreground">
                  The AI uses <strong>MetaCognitiveAnalyzer</strong> to understand your request and decide:
                </p>
                <ul className="text-sm space-y-1 text-muted-foreground ml-4">
                  <li>• What you really want to build</li>
                  <li>• How complex the task is</li>
                  <li>• Which execution strategy to use</li>
                  <li>• What files and structure are needed</li>
                </ul>
              </div>

              <div className="space-y-3">
                <h3 className="font-semibold text-success flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-success"></span>
                  3. Natural Communication
                </h3>
                <p className="text-sm text-muted-foreground">
                  <strong>NaturalCommunicator</strong> generates all messages you see - no templates!
                </p>
                <ul className="text-sm space-y-1 text-muted-foreground ml-4">
                  <li>• Status updates generated by AI</li>
                  <li>• Contextual, natural language</li>
                  <li>• Adapts to your communication style</li>
                </ul>
              </div>

              <div className="space-y-3">
                <h3 className="font-semibold text-green-600 flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-green-600"></span>
                  4. Adaptive Execution
                </h3>
                <p className="text-sm text-muted-foreground">
                  <strong>AdaptiveExecutor</strong> builds using the strategy AI chose:
                </p>
                <ul className="text-sm space-y-1 text-muted-foreground ml-4">
                  <li>• <strong>Instant</strong>: Fast, single-shot generation</li>
                  <li>• <strong>Progressive</strong>: Step-by-step with validation</li>
                  <li>• <strong>Conversational</strong>: Interactive with questions</li>
                  <li>• <strong>Hybrid</strong>: Combines multiple strategies</li>
                </ul>
              </div>

              <div className="pt-4 border-t">
                <p className="text-sm text-center text-muted-foreground">
                  <strong className="text-primary">No hardcoded paths.</strong>{' '}
                  <strong className="text-accent">No template restrictions.</strong>{' '}
                  <strong className="text-success">Pure AI autonomy.</strong>
                </p>
              </div>
            </Card>

            <Card className="p-4 bg-primary/5 border-primary/20">
              <p className="text-sm text-foreground">
                <strong className="text-primary">Frontend Integration:</strong> Your React app subscribes to 
                Supabase realtime channels using <code className="text-primary">useRealtimeAI</code> hook. 
                The edge functions broadcast AI's thinking process as it happens.
              </p>
            </Card>
          </div>
        </div>

        {/* Code Example */}
        <Card className="p-6 bg-card/50">
          <h3 className="text-sm font-semibold mb-3 text-foreground">Frontend Usage Example</h3>
          <pre className="text-xs bg-muted/50 p-4 rounded-lg overflow-x-auto">
            <code>{`// In your React component (e.g., Workspace.tsx)
import { AIThinkingPanel } from '@/components/AIThinkingPanel';

function MyWorkspace() {
  const projectId = '...'; // From route params or context
  const conversationId = '...'; // From route params
  const workspaceName = 'My Project';

  return (
    <div>
      <AIThinkingPanel 
        projectId={projectId}
        conversationId={conversationId}
        workspaceName={workspaceName}
      />
      {/* Rest of your workspace UI */}
    </div>
  );
}

// The AI automatically knows:
// ✓ Which workspace to work in (projectId)
// ✓ What to build (from your request)
// ✓ How to structure files (autonomous decision)
// ✓ What to communicate (AI-generated messages)`}</code>
          </pre>
        </Card>
      </div>
    </div>
  );
}
